import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections.abc import Callable

from .model import Model
from .context_manager import ContextManager

from ..utils.simulator_utils import shifted_softplus, softplus
from ..viz import visualize_matrix, visualize_matrices, visualize_design_configs


class NestedModelFamily:
    def __init__(
        self,
        model: Model,
        prior_fun: dict[str, dict[str, Callable]],
        intrinsic_params: list[str] | None = None,
        regressed_params: list[str] | None = None,
        context_manager: ContextManager | None = None,
        mask_randomizer_kwargs: dict | None = None,
        name: str | None = None,
    ):
        self.name = name
        self.model = model

        if context_manager is None:
            context_manager = ContextManager()
        self.context_manager = context_manager

        if intrinsic_params is None:
            intrinsic_params = list(prior_fun.keys())
        self.intrinsic_params = intrinsic_params
        self.regressed_params = regressed_params

        self.mask_randomizer_kwargs = mask_randomizer_kwargs

        # Detect whether the user-supplied priors are intrinsic priors
        is_intrinsic_priors = True
        for _, v in prior_fun.items():
            if not isinstance(v, dict):
                is_intrinsic_priors = False

        # If they are intrinsic priors, use as is.
        # Otherwise, they are automatically generated by ContextManager
        if is_intrinsic_priors:
            # Use directly (option 1)
            self.prior_fun = prior_fun
        else:
            # Build intrinsic priors internally (option 2)
            self.prior_fun = self.context_manager.build_intrinsic_priors(
                prior_fun=prior_fun,
                free_intrinsics=mask_randomizer_kwargs["free_intrinsics"],
                fixed_intrinsics=mask_randomizer_kwargs["fixed_intrinsics"],
                fixed_values=mask_randomizer_kwargs["fixed_values"],
            )

    @property
    def parameter_names(self) -> list[str]:
        return self.context_manager.parameter_names

    def sample(
        self,
        design_config: dict[str, list[str]] = None,
        num_obs: int = 10,
        num_regressors: int = 2,
        max_num_regressors: int = 5,
        max_num_categories: int = 4,
        link_fun: Callable = shifted_softplus,
        context: dict[str, np.ndarray] | None = None,
        mask_randomizer_kwargs: dict | None = None,
        discrete_prob: float = 0.5,
        free_prob: float = 0.5,
        keep_intercept: bool = True,
        flatten_param_outputs: bool = True,
        debug: bool = False,
        fixed_config: bool = False,
        add_interaction: bool = False,
    ):
        # Create design config and parameter mask, either dynamically or based on user input
        if design_config is None:
            if fixed_config and self.regressed_params is not None:
                design_config = self.context_manager.build_design_config(
                    intrinsic_params=self.intrinsic_params,
                    regressed_params=self.regressed_params,
                    num_regressors=num_regressors,
                    keep_intercept=keep_intercept,
                    add_interaction=add_interaction,
                )
                parameter_mask = self.context_manager.build_parameter_mask(
                    design_config=design_config,
                    intrinsic_params=self.intrinsic_params,
                    max_num_categories=max_num_categories,
                    keep_intercept=keep_intercept,
                    # max_num_regressors=max_num_regressors,
                )
            else:
                if mask_randomizer_kwargs is None:
                    kwargs = self.mask_randomizer_kwargs
                else:
                    kwargs = mask_randomizer_kwargs
                kwargs = kwargs or {}
                parameter_mask, design_config = self.context_manager.build_random_parameter_mask(
                    intrinsic_params=self.intrinsic_params,
                    num_regressors=num_regressors,
                    # max_num_regressors=max_num_regressors,
                    max_num_categories=max_num_categories,
                    keep_intercept=keep_intercept,
                    free_prob=free_prob,
                    free_intrinsics=kwargs.get("free_intrinsics"),
                    fixed_intrinsics=kwargs.get("fixed_intrinsics"),
                    add_interaction=add_interaction,
                )
        else:
            parameter_mask = self.context_manager.build_parameter_mask(
                design_config=design_config,
                intrinsic_params=self.intrinsic_params,
                max_num_categories=max_num_categories,
                keep_intercept=keep_intercept,
                # max_num_regressors=max_num_regressors,
            )

        # Partition regressor keys
        regressor_keys = [k for k in design_config.keys() if k != "1"]
        num_regressors_total = len(regressor_keys)

        # Discrete mask
        main_discrete_mask, discrete_mask = self.context_manager.build_discrete_mask(
            design_config=design_config,
            discrete_prob=discrete_prob,
            keep_intercept=keep_intercept,
        )

        # Check if there is a context for the model
        if context is None and hasattr(self.model, 'build_default_context'):
            context = self.model.build_default_context(num_obs=num_obs)

        # Design matrix
        design_matrix = self.context_manager.build_design_matrix(
            design_config=design_config,
            num_obs=num_obs,
            context=context,
            discrete_prob=discrete_prob,
            keep_intercept=keep_intercept,
            # max_num_regressors=max_num_regressors,
            max_num_categories=max_num_categories,
        )

        # Parameter matrix
        parameter_matrix = self.context_manager.sample_parameter_matrix(
            parameter_mask=parameter_mask,
            prior_fun=self.prior_fun,
            intrinsic_params=self.intrinsic_params,
            keep_intercept=keep_intercept,
        )

        # Compose per-trial intrinsic values
        regressed_parameters = link_fun(design_matrix @ parameter_matrix)

        # Package for model
        params = {
            name: regressed_parameters[:, j].astype(np.float32, copy=False)
            for j, name in enumerate(self.intrinsic_params)
        }

        params = self.model.prepare_params(params=params, num_obs=num_obs, context=context)
        sim_trials = self.model.simulate(params, context=context)

        # Regressor mask
        regressor_mask = self.context_manager.build_regressor_mask(
            num_regressors=num_regressors_total,
            max_num_categories=max_num_categories,
            keep_intercept=keep_intercept
        )

        # Flatten param outputs
        if flatten_param_outputs:
            parameter_mask = parameter_mask.flatten()
            parameter_matrix = parameter_matrix.flatten()

        out = {
            "model_name": f"{self.name}",
            "design_config": design_config,
            "design_matrix": design_matrix,
            "param_mask": parameter_mask,
            "param_matrix": parameter_matrix,
            "sim_trials": sim_trials,
            "discrete_mask": discrete_mask,
            "regressor_mask": regressor_mask,
            "max_num_regressors": max_num_regressors,
            "keep_intercept": keep_intercept,
        }

        if debug:
            for k, v in out.items():
                if isinstance(v, np.ndarray):
                    print(k, v.shape)
                elif isinstance(v, list):
                    for i in v:
                        print(i)
                elif isinstance(v, dict):
                    print(v.keys())
                else:
                    print(k, v)

        return out

    def batch_sample(
        self,
        batch_size: int,
        num_obs: int | None = None,
        design_config: dict[str, list[str]] | None = None,
        num_regressors: int | None = None,
        context: dict[str, np.ndarray] | None = None,
        min_num_obs: int = 10,
        max_num_obs: int = 600,
        min_num_regressors: int = 0,
        max_num_regressors: int = 3,
        max_num_categories: int = 3,
        discrete_prob: float = 0.5,
        keep_intercept: bool = True,
        remove_intercept_on_collate: bool = False,
        mask_randomizer_kwargs: dict | None = None,
        flatten_param_outputs: bool = True,
        fixed_config: bool = False,
        add_interaction: bool = False,
    ) -> list[dict] | dict:
        # Sample num_obs and num_regressors per batch element if not provided
        if num_obs is None:
            num_obs = np.random.randint(min_num_obs, max_num_obs + 1)

        if num_regressors is None:
            num_regressors_array = np.random.randint(min_num_regressors, max_num_regressors + 1, size=batch_size)
        else:
            num_regressors_array = np.full(batch_size, num_regressors)

        if mask_randomizer_kwargs is None:
            mask_randomizer_kwargs = self.mask_randomizer_kwargs

        # Initialize batch and keep track of the maximum num_obs
        list_batch = []

        for i in range(batch_size):

            num_regressors = num_regressors_array[i]

            # Resolve context per item:
            if context is None:
                if hasattr(self.model, 'build_default_context'):
                    ctx_i = self.model.build_default_context(num_obs=num_obs)
                else:
                    ctx_i = None
            elif callable(context):
                # If the whole context is a callable, let it build a dict with n_obs
                ctx_i = context(num_obs)
            else:
                # If context is a dict, allow callable values that depend on n_obs
                ctx_i = {}
                for k, v in context.items():
                    ctx_i[k] = v(num_obs) if callable(v) else v

            sim_instance = self.sample(
                design_config=design_config,
                num_obs=num_obs,
                context=ctx_i,
                mask_randomizer_kwargs=mask_randomizer_kwargs,
                num_regressors=num_regressors,
                discrete_prob=discrete_prob,
                keep_intercept=keep_intercept,
                # max_num_regressors=max_num_regressors,
                max_num_categories=max_num_categories,
                flatten_param_outputs=flatten_param_outputs,
                fixed_config=fixed_config,
                add_interaction=add_interaction,
            )

            sim_instance["num_obs"] = num_obs
            sim_instance["num_regressors"] = num_regressors_array[i]
            sim_instance["max_num_regressors"] = max_num_regressors
            sim_instance["max_num_categories"] = max_num_categories
            list_batch.append(sim_instance)

        batch = self.collate(
            list_batch,
            flatten_param_outputs=flatten_param_outputs,
            remove_intercept=remove_intercept_on_collate
        )
        return batch

    def collate(
        self,
        list_batch: list[dict],
        flatten_param_outputs: bool = True,
        remove_intercept: bool = True
    ) -> dict[str, np.ndarray]:

        # Infer batch size
        batch_size = len(list_batch)
        num_params = len(self.intrinsic_params)
        max_num_obs = max(b["num_obs"] for b in list_batch)
        # max_num_regressors = max(b["num_regressors"] for b in list_batch)
        max_num_regressors = list_batch[0]["max_num_regressors"]
        max_num_categories = list_batch[0]["max_num_categories"]

        # Calculate max column width
        block_width = max_num_categories - 1
        max_total_regressors = max_num_regressors * (max_num_regressors + 1) // 2
        max_num_cols = max_total_regressors * block_width + (1 if list_batch[0]["keep_intercept"] else 0)

        if flatten_param_outputs:
            param_outputs_shape = (batch_size, max_num_cols * num_params)
        else:
            param_outputs_shape = (batch_size, max_num_cols, num_params)

        # Preallocate arrays
        design_matrices = np.zeros((batch_size, max_num_obs, max_num_cols))
        param_masks = np.zeros(param_outputs_shape)
        param_matrices = np.zeros(param_outputs_shape)
        regressor_masks = np.zeros((batch_size, max_num_cols))
        discrete_masks = -np.ones((batch_size, max_total_regressors))
        num_obs_array = np.zeros((batch_size, 1))
        num_regressors_array = np.zeros((batch_size, 1))

        # Collect lists
        model_names, design_configs = [], []

        # Initialize sim_data dict with zero arrays
        sim_keys = list_batch[0]["sim_trials"].keys()
        sim_data = {k: np.empty((batch_size, max_num_obs, 1)) for k in sim_keys}

        # Collate batch entries
        for i, b in enumerate(list_batch):
            model_names.append(b["model_name"])
            design_configs.append(b["design_config"])

            # Pad design_matrix, param_mask, param_matrix, and regressor_mask to max_num_regressors
            num_obs = b["num_obs"]
            num_regressors = b["num_regressors"]
            num_cols = b["design_matrix"].shape[1]

            design_matrices[i, :num_obs, :num_cols] = b["design_matrix"]

            if flatten_param_outputs:
                param_masks[i, :num_cols * num_params] = b["param_mask"]
                param_matrices[i, :num_cols * num_params] = b["param_matrix"]
            else:
                param_masks[i, :num_cols, :num_params] = b["param_mask"]
                param_matrices[i, :num_cols, :num_params] = b["param_matrix"]

            regressor_masks[i, :num_cols] = b["regressor_mask"]
            discrete_masks[i, :b["discrete_mask"].shape[0]] = b["discrete_mask"]
            num_obs_array[i] = b["num_obs"]
            num_regressors_array[i] = b["num_regressors"]

            for k in sim_keys:
                v = b["sim_trials"][k]
                sim_data[k][i, :v.shape[0]] = v

        if remove_intercept:
            design_matrices = design_matrices[:, :, 1:]

        return {
            "model_names": model_names,
            "design_configs": design_configs,
            "design_matrices": design_matrices,
            "param_masks": param_masks,
            "param_matrices": param_matrices,
            "sim_data": sim_data,
            "regressor_masks": regressor_masks,
            "discrete_masks": discrete_masks,
            "num_obs": num_obs_array,
            "num_regressors": num_regressors_array,
            "max_num_regressors": max_num_regressors,
            "max_num_categories": max_num_categories,
        }

    def check_regressed_priors(
        self,
        design_config: dict[str, list[str]],
        num_draws: int = 200,
        num_obs: int = 200,
        max_num_categories: int = 4,
        link_fun: Callable = softplus,
        context: dict[str, np.ndarray] | None = None,
        discrete_prob: float = 0.5,
        keep_intercept: bool = True,
        run_simulator: bool = False,
        fixed_config: bool = True,   # keep design_config as provided
        add_interaction: bool = False,
        return_coeff_draws: bool = True,
        seed: int | None = None,
        plot: bool = True
    ) -> dict:
        """
        Draw from the induced prior over per-trial intrinsic parameters for a given design_config.

        Returns
        -------
        out : dict
            - design_config
            - column_labels
            - theta_draws: (num_draws, num_obs, num_intrinsic_params)
            - (optional) coef_draws: (num_draws, num_cols, num_intrinsic_params)
            - (optional) sim_draws: list[dict] of simulator outputs, length num_draws
        """
        if seed is not None:
            np.random.seed(seed)

        # Resolve context (unstandardized X behavior already comes from ContextManager.build_design_matrix)
        if context is None and hasattr(self.model, "build_default_context"):
            context = self.model.build_default_context(num_obs=num_obs)

        # Build mask from provided design_config (the key part: "any design config")
        parameter_mask = self.context_manager.build_parameter_mask(
            design_config=design_config,
            intrinsic_params=self.intrinsic_params,
            max_num_categories=max_num_categories,
            keep_intercept=keep_intercept,
        )

        # Build fixed labels for interpretability
        column_labels = self.context_manager.build_column_labels(
            design_config=design_config,
            max_num_categories=max_num_categories,
            keep_intercept=keep_intercept,
        )

        # We re-sample X each draw unless the user supplies it via context
        # (context keys like "u_1" etc. already override columns in build_design_matrix).
        theta_draws = []
        coef_draws = [] if return_coeff_draws else None
        sim_draws = [] if run_simulator else None

        # For intercept-only induced priors (one value per draw per intrinsic param)
        intercept_theta_draws = []  # list of (num_intrinsic_params,)
        intercept_idx = None
        if keep_intercept and ("1" in column_labels):
            intercept_idx = column_labels.index("1")

        for _ in range(num_draws):
            X = self.context_manager.build_design_matrix(
                design_config=design_config,
                num_obs=num_obs,
                context=context,
                discrete_prob=discrete_prob,
                keep_intercept=keep_intercept,
                max_num_categories=max_num_categories,
                main_discrete_mask=None,  # allow randomness unless you pass a fixed one
            )

            B = self.context_manager.sample_parameter_matrix(
                parameter_mask=parameter_mask,
                prior_fun=self.prior_fun,
                intrinsic_params=self.intrinsic_params,
                keep_intercept=keep_intercept,
            )

            if intercept_idx is not None:
                theta0 = link_fun(B[intercept_idx, :])  # (num_intrinsic_params,)
                intercept_theta_draws.append(theta0.astype(np.float32, copy=False))

            theta = link_fun(X @ B)  # (num_obs, num_intrinsic_params)
            theta_draws.append(theta.astype(np.float32, copy=False))

            if return_coeff_draws:
                coef_draws.append(B.astype(np.float32, copy=False))

            if run_simulator:
                params = {
                    name: theta[:, j].astype(np.float32, copy=False)
                    for j, name in enumerate(self.intrinsic_params)
                }
                params = self.model.prepare_params(params=params, num_obs=num_obs, context=context)
                sim = self.model.simulate(params, context=context)
                sim_draws.append(self.model.simulate(params, context=context))

        theta_draws = np.stack(theta_draws, axis=0)

        if plot:
            f, axarr = plt.subplots(1, len(self.intrinsic_params), figsize=(15, 3))
            if len(self.intrinsic_params) == 1:
                axarr = [axarr]

            intercept_theta_draws = (
                np.stack(intercept_theta_draws, axis=0)
                if (intercept_idx is not None and len(intercept_theta_draws) > 0)
                else None
            )

            for i, ax in enumerate(axarr):
                # Full regressed prior (includes X effects)
                sns.histplot(theta_draws[:, 0, i], ax=ax, kde=True, stat="density", label="regressed")

                # Intercept-only induced prior overlay
                if intercept_theta_draws is not None:
                    sns.histplot(
                        intercept_theta_draws[:, i],
                        ax=ax,
                        kde=True,
                        stat="density",
                        element="step",
                        fill=False,
                        label="intercept only",
                    )
                    ax.legend()

                ax.set_xlabel(self.intrinsic_params[i])

            f.tight_layout()
            return f

        out = {
            "design_config": design_config,
            "column_labels": column_labels,
            "intrinsic_params": self.intrinsic_params,
            "theta_draws": theta_draws,
        }
        if return_coeff_draws:
            out["coef_draws"] = np.stack(coef_draws, axis=0)  # (D, C, P)
        if run_simulator:
            out["sim_draws"] = sim_draws

        return out
